// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/adamnasrudin03/go-template/app/modules/user/dto"
	mock "github.com/stretchr/testify/mock"

	models "github.com/adamnasrudin03/go-template/app/models"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// CheckIsDuplicate provides a mock function with given fields: ctx, input
func (_m *UserRepository) CheckIsDuplicate(ctx context.Context, input dto.DetailReq) error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CheckIsDuplicate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.DetailReq) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateCache provides a mock function with given fields: ctx, key, data
func (_m *UserRepository) CreateCache(ctx context.Context, key string, data interface{}) {
	_m.Called(ctx, key, data)
}

// DelCache provides a mock function with given fields: ctx, key
func (_m *UserRepository) DelCache(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for DelCache")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCache provides a mock function with given fields: ctx, key, res
func (_m *UserRepository) GetCache(ctx context.Context, key string, res interface{}) {
	_m.Called(ctx, key, res)
}

// GetDetail provides a mock function with given fields: ctx, input
func (_m *UserRepository) GetDetail(ctx context.Context, input dto.DetailReq) (*models.User, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetDetail")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.DetailReq) (*models.User, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.DetailReq) *models.User); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.DetailReq) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetList provides a mock function with given fields: ctx, params
func (_m *UserRepository) GetList(ctx context.Context, params dto.ListUserReq) ([]models.User, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetList")
	}

	var r0 []models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.ListUserReq) ([]models.User, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.ListUserReq) []models.User); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.ListUserReq) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertLog provides a mock function with given fields: ctx, input
func (_m *UserRepository) InsertLog(ctx context.Context, input models.Log) error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for InsertLog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Log) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateSpecificField provides a mock function with given fields: ctx, input
func (_m *UserRepository) UpdateSpecificField(ctx context.Context, input models.User) error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSpecificField")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.User) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Updates provides a mock function with given fields: ctx, input
func (_m *UserRepository) Updates(ctx context.Context, input models.User) (*models.User, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Updates")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.User) (*models.User, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.User) *models.User); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.User) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
